export const routes = {
  home: "/",
  fallback: "*",
  productList: "/products",
  product: "/product/:id",
  basket: "/basket",
  login: "/login",
  logout: "/logout",
  register: "/register",
  profile: "/profile",
  admin: "/administrator",
  favorite: "/favorite",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password/:token",
};
