export type Product = {
  id: number;
  img: string;
  name: string;
  cost: number;
  type: string;
  brand: string;
  rating: string;
  desk:string;
  discount?: number;
};

export const products = [

  {
    id: 1,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 2,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Xiaomi 10",
    cost: 2000,
    type: "Phones",
    brand: "Xiaomi",
    desk: "Самы епта четки мабильник нах",
    discount: 0.5,
    rating: "5",
  },
  {
    id: 3,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Xiaomi 1110",
    cost: 2000,
    type: "Laptops",
    brand: "Xiaomi",
    desk: "",
    rating: "5",
  },
  {
    id: 4,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Xiaomi 10",
    cost: 2000,
    type: "Phones",
    brand: "Xiaomi",
    desk: "dsfasfd",
    rating: "1",
  },
  {
    id: 5,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Xiaomi 10",
    cost: 2000,
    type: "Phones",
    brand: "Xiaomi",
    desk: "reergerg",
    rating: "нет отзывов",
  },
  {
    id: 6,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Xiaomi 10",
    cost: 2000,
    type: "Phones",
    brand: "Xiaomi",
    desk: "авыф",
    rating: "2",
  },
  {
    id: 7,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 8,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 9,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 10,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 11,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 12,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 13,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "5",
  },
  {
    id: 14,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Iphone 10",
    cost: 2000,
    type: "Phones",
    brand: "Apple",
    desk: "",
    rating: "4",
  },
  {
    id: 15,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 16,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 17,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 18,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 19,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 20,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 21,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 22,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 23,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 24,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 25,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 26,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
  {
    id: 27,
    img: "https://w7.pngwing.com/pngs/450/269/png-transparent-space-gray-iphone-x-showing-ios-and-iphone-4-iphone-8-plus-iphone-5-iphone-x-iphone-apple-gadget-electronics-mobile-phone-thumbnail.png",
    name: "Macbook 10",
    cost: 2000,
    type: "Laptops",
    brand: "Apple",
    desk: "",
    discount: 0.2,
    rating: "5",
  },
];
